Make it installable in both old (bro) and new (zeek)
Trying to avoid

```
zkg install top-dns
error: failed to resolve dependencies: package "zeek/corelight/top-dns" has invalid dependency "bro/sethhall/domain-tld": package name not found in sources and also not a usable git URL (invalid or inaccessible, use -vvv for details)
```
in a way that it can work on an old install (which thinks everything is `bro/path/bar` instead of `zeek\path\bar`).